project_id = "gtaknyaxqeuyvbacecqc"

[functions.categorize-message]
verify_jwt = false

[functions.slack-notification]
verify_jwt = false

[functions.simulate-messages]
verify_jwt = false

[functions.categorize-email]
verify_jwt = false

[functions.suggest-reply]
verify_jwt = false

[functions.simulate-emails]
verify_jwt = false